#' CDEnrich Demonstration Data
#'
#' Small simulated datasets used in CDEnrich examples and vignettes.
#'
#' The ORA and ssGSEA datasets are built from the recommended Ferroptosis
#' gene set (FerrDb V2, PMID: 36305834), and the GSEA datasets from the
#' representative Apoptosis gene set (PMID: 37968457). Background genes
#' are synthetic placeholders (BackgroundGene_1 ... BackgroundGene_3000).
#' All datasets are generated by \code{data-raw/demo_data.R} with a fixed
#' random seed and are fully reproducible.
#'
#' @return This help page is an overview of the demonstration datasets
#'   shipped with CDEnrich; see the individual dataset pages for details.
#'
#' @name CDEnrich_demo_data
#' @keywords datasets
NULL

#' Demonstration Background Gene Universe
#'
#' A character vector combining the recommended Ferroptosis gene set with
#' 3000 synthetic background genes. Used as the ORA background universe.
#'
#' @docType data
#' @name demo_all_genes
#' @usage data(demo_all_genes)
#' @format A character vector of gene symbols.
#' @keywords datasets
"demo_all_genes"

#' Demonstration DEG List for Single-Group ORA
#'
#' Up to 100 real genes taken from the recommended Ferroptosis gene set,
#' providing a strong and reproducible enrichment signal.
#'
#' @docType data
#' @name demo_deg
#' @usage data(demo_deg)
#' @format A character vector of gene symbols.
#' @keywords datasets
"demo_deg"

#' Demonstration DEG List for Targeted ORA
#'
#' Identical to \code{demo_deg}; kept as a separate object so the targeted
#' ORA example reads as an independent workflow.
#'
#' @docType data
#' @name demo_targeted_deg
#' @usage data(demo_targeted_deg)
#' @format A character vector of gene symbols.
#' @keywords datasets
"demo_targeted_deg"

#' Demonstration DEG Lists for Multi-Group ORA
#'
#' A named list with two groups: Control (15 Ferroptosis genes) and
#' Treatment (up to 100 Ferroptosis genes).
#'
#' @docType data
#' @name demo_deg_list
#' @usage data(demo_deg_list)
#' @format A named list of two character vectors.
#' @keywords datasets
"demo_deg_list"

#' Demonstration Ranked Gene List for Single-Group GSEA
#'
#' A decreasingly sorted named numeric vector. All genes from the
#' representative Apoptosis gene set are assigned large positive ranking
#' statistics, creating a clear enrichment signal.
#'
#' @docType data
#' @name demo_rank_apop
#' @usage data(demo_rank_apop)
#' @format A decreasingly sorted named numeric vector.
#' @keywords datasets
"demo_rank_apop"

#' Demonstration Ranked Gene Lists for Multi-Group GSEA
#'
#' A named list of two decreasingly sorted numeric vectors: Control has no
#' intentionally introduced signal, Treatment carries the same strong
#' Apoptosis signal as \code{demo_rank_apop}.
#'
#' @docType data
#' @name demo_rank_apop_list
#' @usage data(demo_rank_apop_list)
#' @format A named list of two decreasingly sorted numeric vectors.
#' @keywords datasets
"demo_rank_apop_list"

#' Demonstration Expression Matrix for ssGSEA
#'
#' A numeric expression matrix with genes as rows and 12 samples as
#' columns. Ferroptosis genes are shifted upwards in Treatment samples,
#' creating higher Ferroptosis activity in that group.
#'
#' @docType data
#' @name demo_expr
#' @usage data(demo_expr)
#' @format A numeric matrix (genes x samples).
#' @keywords datasets
"demo_expr"

#' Demonstration Sample Groups for ssGSEA
#'
#' A factor assigning the 12 samples of \code{demo_expr} to Control and
#' Treatment groups (6 samples each).
#'
#' @docType data
#' @name demo_group
#' @usage data(demo_group)
#' @format A factor with two levels (Control, Treatment).
#' @keywords datasets
"demo_group"
